[project]
name = "forms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mdrp", email = "mdrpdeveloper@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.14.3",
    "async-timeout>=5.0.1",
    "beautifulsoup4>=4.15.0",
    "emoji>=2.16.0",
    "html2image>=2.0.7",
    "lxml>=6.1.3",
    "numpy>=2.5.3",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "pyfiglet>=1.0.4",
    "pymupdf>=1.28.2",
    "pypdf>=6.19.0",
    "pyperclip>=1.11.0",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "selenium>=4.49.0",
    "urllib3>=2.8.0",
    "webdriver-manager>=4.1.2",
]

[project.scripts]
forms = "forms:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
