const depts_array = ["AMBULANCE (รถพยาบาล)", "ANESTHESIA (วิสัญญี)", "ART-LAB (ศูนย์ผู้มีบุตรยาก)", "BME-PYT3", "CATH-LAB", "CHECK-UP (ตรวจสุขภาพ)", "CORPORATE CUSTOMER SERVICE", "CSSD (จ่ายกลาง)", "DENTAL (ทันตกรรม)", "DIABETIC&METABOLIC(เบาหวาน)", "EENT( หูตาคอจมูก)", "EMERGENCY( ฉุกเฉิน)", "GASTROINTESTINAL LABORATORY(GI)", "HEMODIALYSIS (ไตเทียม)", "HOPD CENTER (ศุนย์มะเร็ง)", "HOUSEKEEPING", "INFECTION CONTROL ( IC)", "INTENSIVE CARE UNIT(ผู้ป่วยหนัก)", "LABOR ROOM(ห้องคลอด)", "LABORATORY", "MARKETING", "NURSERY(เด็กอ่อน)", "NURSING DEPARTMENT", "OBSERVE(สังเกตอาการ)", "OPD CARDIO(ศูนย์หัวใจ)", "OPD COUNTER NURSE (CN คัดกรอง)", "OPD HEAD NECK BREAST(ศุนย์เต้านม)", "OPD MEDICINE(อายุกรรม)", "OPD NEURO (ศูนย์สมอง)", "OPD OB/GYN(ศุนย์สุขภาพหญิง)", "OPD ORTHOPAEDICS (ศูนย์กล้ามเนื้อและกระดูก)", "OPD PEDIATRIC( แผนกเด็ก)", "OPD SURGERY(ศัลยกรรม)", "OPD UROLOGY (ทางเดินปัสสาวะ)", "OPERATING ROOM(ห้องผ่าตัด)", "PHARMACY(เภสัชกรรม ห้องยา)", "PHARMACY-STORE (คลังยา)", "PHYATHAI BEAUTY CENTER (PBC ความงาม)", "PHYSICAL THERAPY( กายภาพ)", "PICU", "PWA LIFE CENTER", "PWA ชะลอวัย", "VEHICLE", "WARD 10", "WARD 11", "WARD 12", "WARD 14", "WARD 15", "WARD 17", "WARD 7", "WARD 8", "WARD 9", "WAREHOUSE", "X-RAY", "รับส่ง", "ห้องเก็บของชั้น 19"]

const depts_id = {
  "ANESTHESIA (วิสัญญี)": 244,
  "ART-LAB (ศูนย์ผู้มีบุตรยาก)": 162,
  "CATH-LAB": 232,
  "CHECK-UP (ตรวจสุขภาพ)": 151,
  "CORPORATE CUSTOMER SERVICE": 551,
  "CSSD (จ่ายกลาง)": 245,
  "DENTAL (ทันตกรรม)": 291,
  "DIABETIC&METABOLIC(เบาหวาน)": 411,
  "EENT( หูตาคอจมูก)": 271,
  "EMERGENCY( ฉุกเฉิน)": 101,
  "GASTROINTESTINAL LABORATORY(GI)": 351,
  "HEMODIALYSIS (ไตเทียม)": 212,
  "HOPD CENTER (ศุนย์มะเร็ง)": 211,
  "INFECTION CONTROL ( IC)": 123,
  "INTENSIVE CARE UNIT(ผู้ป่วยหนัก)": 241,
  "LABOR ROOM(ห้องคลอด)": 163,
  "LABORATORY": 311,
  "MARKETING": 571,
  "NURSERY(เด็กอ่อน)": 167,
  "NURSING DEPARTMENT": 671,
  "OPD CARDIO(ศูนย์หัวใจ)": 231,
  "OPD COUNTER NURSE (CN คัดกรอง)": 381,
  "OPD HEAD NECK BREAST(ศุนย์เต้านม)": 134,
  "OPD MEDICINE(อายุกรรม)": 111,
  "OPD NEURO (ศูนย์สมอง)": 181,
  "OPD OB/GYN(ศุนย์สุขภาพหญิง)": 161,
  "OPD PEDIATRIC( แผนกเด็ก)": 171,
  "OPD SURGERY(ศัลยกรรม)": 131,
  "OPD UROLOGY (ทางเดินปัสสาวะ)": 133,
  "OPERATING ROOM(ห้องผ่าตัด)": 243,
  "PHARMARCY(เภสัชกรรม ห้องยา)": 321,
  "PHARMACY-STORE (คลังยา)": 322,
  "PHYATHAI BEAUTY CENTER (PBC ความงาม)": 191,
  "PHYSICAL THERAPY( กายภาพ)": 331,
  "PICU": 179,
  "PWA LIFE CENTER": 193,
  "PWA ชะลอวัย": 193,
  "WARD 10": 254,
  "WARD 11": 174,
  "WARD 12": 175,
  "WARD 15": 255,
  "WARD 17": 246,
  "WARD 7": 164,
  "WARD 8": 238,
  "WARD 9": 185,
  "X-RAY": 301,
  "รับส่ง": 653,
};